name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for pushing back to the repository
      pages: write # Required for GitHub Pages deployment (if applicable)
      id-token: write # Required for some external deployment providers
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install # Or yarn install

      - name: Build React App
        run: npm run build # Or yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Or ./dist if that's your build directory
